<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR49buns\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR49buns/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerR49buns.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerR49buns\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerR49buns\appDevDebugProjectContainer([
    'container.build_hash' => 'R49buns',
    'container.build_id' => '7b31a518',
    'container.build_time' => 1610567433,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR49buns');
