apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: be-11
spec:
  replicas: 1
  selector:
    matchLabels:
    app: be-11
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: be-11
    spec:
      containers:
      - env:
        - name: DBS_NAME
          value: db_11
        - name: DBS_USER
          value: user_11
        - name: DBS_PASSWD
          value: root
        image: "172.20.83.35:5000/11:latest"
        imagePullPolicy: "Always"
        name: be-11
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
status: {}