apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: be-11
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30011
  - name: "443"
    port: 443
    targetPort: 443
    nodePort: 30111
  selector:
    app: be-11
  type: NodePort
status:
loadBalancer: {}